title: vetzal.ca
email: stacey@vetzal.com
description: >
  Welcome to vetzal.ca, the connecting point for members of the Vetzal family.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vetzal.ca" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@svetzal"
github_username: svetzal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
